### ISSUE TITLE
Activity Bot status

### ISSUE THREAD

**Issue by thekittygirl** [benji7425/discord-activity-monitor#21]
Is ActivityBot being retired? It appears to have been 'offline' for quite some time, and I noticed the name of the bot changed to "benji7425.io/migrate" — which, hopefully, the word "migrate" means that it is simply being moved, not discontinued! It is a good bot and has been very helpful in my server! Thank you!

**Comment by benji7425** [comment]
Hey! The public version of Activity Monitor is no longer provided as a public host, but you can still use it. The name 'benji7425.io/migrate' is a URL you can visit where the change is explained in detail along with how you can easily set up your own version.

I regret that I had no easy way to communicate this to everyone. For those in my support server there were regular updates for a month leading up to this change, but I had no way to communicate directly with those who hadn't joined.

If you want to learn more you can visit [benji7425.io/migrate](https://benji7425.io/migrate) which will explain the reasoning and also how to migrate.
