### ISSUE TITLE
Voice channel assign active role

### ISSUE THREAD

**Issue by mxsmvn** [benji7425/discord-activity-monitor#22]
How to not assign active role to user who just join leave voice channel ?

**Comment by benji7425** [comment]
There is no configuration option to disable this but it would be possible to achieve by modifying the code if you are manual deployment. You would need to remove lines 13-17 in [src/core/activity-registerer.ts](https://github.com/benji7425/discord-activity-monitor/blob/master/src/core/activity-registerer.ts#L13) and run `npm run full-start` again.

**Comment by mxsmvn** [comment]
Thanks a lot
