### ISSUE TITLE
NPM Run Build Step Failure

### ISSUE THREAD

**Issue by ltcptgeneral** [benji7425/discord-activity-monitor#4]
getting this error whenever I try to run npm run build after running npm install

npm run build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alu/.npm/_logs/2019-05-20T19_09_23_799Z-debug.log

**Comment by lcswolf** [comment]
same issue here trying to install on windows

**Comment by benji7425** [comment]
The current master version isn't actually quite release ready just yet, I was maybe a little too eager in pushing it to the main branch. If you want the latest stable build you can find it on the [releases page](https://github.com/benji7425/discord-activity-monitor/releases), and the matching instructions are available on the [legacy branch](https://github.com/benji7425/discord-activity-monitor/tree/legacy).

The current master branch is my still WIP beta re-write, which will be releasing soon.

**Comment by benji7425** [comment]
I have added a note to [the release page](https://github.com/benji7425/discord-activity-monitor/releases/tag/v3.5.0) pointing to the correct instructions in case others face the same issue. Thanks for pointing it out, sorry for the confusion.
